### ISSUE TITLE
[STA] Kann keine Nachrichten absetzen

### ISSUE THREAD

**Issue by ChrisMalewski** [52North/wv-sensor-web-rest-api#6]
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.wv.javatest;

import org.eclipse.paho.client.mqttv3.*;
import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence;

import java.net.URI;
import java.net.URISyntaxException;

/**
 * A sample application that demonstrates how to use the Paho MQTT v3.1 Client
 * blocking API.
 */
public class Subscriber implements MqttCallback {

    private final int qos = 1;
    private String topic = "v1.0/Datastreams(1)/Observations";
    private MqttClient client;

    public Subscriber(String uri) throws MqttException, URISyntaxException {
        this(new URI(uri));
    }

    public Subscriber(URI uri) throws MqttException {
        String host = String.format("tcp://%s:%d", uri.getHost(), uri.getPort());
        String[] auth = this.getAuth(uri);
        String username = auth[0];
        String password = auth[1];
        String clientId = "MQTT-Java-Example";
        if (!uri.getPath().isEmpty()) {
            this.topic = uri.getPath().substring(1);
        }

        MqttConnectOptions conOpt = new MqttConnectOptions();
        conOpt.setCleanSession(true);
        conOpt.setUserName(username);
        conOpt.setPassword(password.toCharArray());

        this.client = new MqttClient(host, clientId, new MemoryPersistence());
        this.client.setCallback(this);
        this.client.connect(conOpt);

        this.client.subscribe(this.topic, qos);
    }

    private String[] getAuth(URI uri) {
        String a = uri.getAuthority();
        String[] first = a.split("@");
        return first[0].split(":");
    }

    public void sendMessage(String payload) throws MqttException {
        MqttMessage message = new MqttMessage(payload.getBytes());
        message.setQos(qos);
        this.client.publish(this.topic, message); // Blocking publish
    }

    /**
     * @see MqttCallback#connectionLost(Throwable)
     */
    public void connectionLost(Throwable cause) {
        System.out.println("Connection lost because: " + cause);
        System.exit(1);
    }

    /**
     * @see MqttCallback#deliveryComplete(IMqttDeliveryToken)
     */
    public void deliveryComplete(IMqttDeliveryToken token) {
    }

    /**
     * @see MqttCallback#messageArrived(String, MqttMessage)
     */
    public void messageArrived(String topic, MqttMessage message) throws MqttException {
        System.out.println(String.format("[%s] %s", topic, new String(message.getPayload())));
    }

    public static void main(String[] args) throws MqttException, URISyntaxException {
         Subscriber s = new Subscriber("tcp://localhost:1883/sensorthings/sta");

        
//        s.sendMessage("Hello");
        s.sendMessage("{\"result\": \"100\"}");
        
        s.sendMessage("{\"result\": \"200\"}");
    }
}

**Comment by CarstenHollmann** [comment]
_Connection-URL_ 
- müsste nur `tcp://localhost:1883/` sein, also OHNE `sensorthings/sta`.

_Topic_
- Ist das Topic in deinem Code `v1.0/Datastreams(1)/Observations` ? Bei unserer STA-Version wird die Versionsangabe nicht erwartet. Das Topic lautet `Datastreams(1)/Observations`.

_Message_
- Die bereitgestellte Version erwartet eine `phenomenonTime`. In zukünftigen Versionen ist die `phenomenonTime` nicht mehr nötig und die Angabe das `result` reicht dann aus,

**Comment by ChrisMalewski** [comment]
Das habe ich eingestellt und bekomme einen Connection Refused Error.
Gibt es besondere Einstellungen, die ich im Tomcat beachten muss?

**Comment by ChrisMalewski** [comment]
Es funktioniert wunderbar!
